
.PHONY: clean run

build: build-plain

include ../Makefile_common

run: run-common

# This called build! 
# run: 
# 	cd ../instrumented;\
#   (/usr/bin/time -f "SELFTIMED %e\nuser %U\nsys %S\n" ./lbm 3000 reference.dat 0 0 data/ref/input/100_100_130_ldc.of) 2>&1 ;\

clean:
