.PHONY: default clean run

include ../Makefile_common
default: 
	echo "Postponing to run"


build: build-plain
#	cd ../src;\
#	make CFLAGS='-O2'

DATADIR=/u/crest-team/ubiprof_data

run: run-common

# run: build
# 	cd ../src;\
#   (/usr/bin/time -f "SELFTIMED %e\nuser %U\nsys %S\n" ./blackscholes 8 $(DATADIR)/blackscholes_data.input \dev\null) 2>&1 ;\

clean:
