

include ../Makefile_common

# Temp, set this globally:
# DYNAPROF_ROOT=`pwd`/../../../../

# ./setup.sh direct_10
# ./configure CC=icc LIBS='libdynaprof.a libzca-toggle.a -lelf' CLFAGS='-O2';\
# make;\

build: build-dynaprof

run: run-common
