
.PHONY: default clean run

#all: clean run	
default: 
	echo "Postponing to run" 

build: build-plain

include ../Makefile_common

run: run-common

  # 	cd ../instrumented;\
  # (/usr/bin/time -f "SELFTIMED %e\nuser %U\nsys %S\n" ./perlbench -Ilib test/input/diffmail.pl 4 800 10 17 19 300) 2>&1 ;\

clean:
