
.PHONY: clean run

build: build-plain

include ../Makefile_common

run: run-common

clean:


# .PHONY: all clean run

# all: clean run	

# build:
# 	cd ../BarnesHut;\
# 	make clean;\
# 	make 

# DATADIR=/u/crest-team/ubiprof_data

# run: build
# 	cd ../BarnesHut;\
#   (/usr/bin/time -f "SELFTIMED %e\nuser %U\nsys %S\n" ./nbody $(DATADIR)/nbody_data.input) 2>&1 ;\

# clean:
