
.PHONY: clean run

build: build-plain

include ../Makefile_common

run: run-common

clean:

# .PHONY: all clean run

# all: clean run	

# build:
# 	cd ..;./setup.sh 
# 	cd ../instrumented;\
# 	make clean;\
# 	make CFLAGS='-O2'

# run: build
# 	cd ../instrumented;\
#   (/usr/bin/time -f "SELFTIMED %e\nuser %U\nsys %S\n" ./sjeng test/input/test.txt) 2>&1 ;\

# clean:
